linters:
  enable-all: true
  disable:
    - structcheck
    - ifshort
    - deadcode
    - varcheck
    - exhaustivestruct
    - nosnakecase
    - golint
    - maligned
    - interfacer
    - scopelint
    - godox
