linters:
  enable-all: true
  disable:
    - exportloopref
    # - linters above this line are deprecated
    - godox
    - depguard
    - gochecknoglobals
    - forbidigo
    - mnd
    # - linters below this line, I intend to get to at some point
    - cyclop
    - tagliatelle
    - err113
    - nestif
    - funlen
    - gocognit

linters-settings:
  ireturn:
    allow:
      - Piece
      - error

  varnamelen:
    ignore-names:
      - err
      - wg
      - tt
      - sb
      - sq
      - Wp
      - Wn
      - Wb
      - Wr
      - Wq
      - Wk
      - Bp
      - Bn
      - Bb
      - Br
      - Bq
      - Bk
      - Wa
      - Ba

  dupl:
    # token count to trigger issue. 150 by default
    threshold: 200
