go_library(
    name = "position",
    srcs = ["position.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/board",
    ],
)

go_test(
    name = "position_test",
    srcs = ["position_test.go"],
    deps = [":position"],
)
