go_library(
    name = "piece",
    srcs = ["piece.go"],
    visibility = [
        "//plz-out/gen/src/eval:all",
        "//plz-out/gen/src/moves:all",
        "//plz-out/gen/src/position:all",
        "//plz-out/tmp/src/position/_position_test#lib._build/src/position:all",
        "//src/engine:all",
        "//src/eval:all",
        "//src/moves:all",
        "//src/position:all",
    ],
)
