name: Build and test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5

    - name: Go build
      run: go build ./...

    - name: Go test
      run: go test ./...

