name: Main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Please build
      run: ./pleasew build //... --plain_output

    - name: Please test
      run: ./pleasew test //... --plain_output

